In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("C:/Users/HP/Desktop/Imarticus Learning/Datasets/Social_Network_Ads.csv")
print(df)
df.head()

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

    User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [3]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [4]:
df=pd.get_dummies(df)
df.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Female',
       'Gender_Male'],
      dtype='object')

In [6]:
x=df[['Age','EstimatedSalary','Gender_Female','Gender_Male']]
y=df['Purchased']
print(x)
print(y)

      Age  EstimatedSalary  Gender_Female  Gender_Male
0    19.0          19000.0              0            1
1    35.0          20000.0              0            1
2    26.0          43000.0              1            0
3    27.0          57000.0              1            0
4    19.0          76000.0              0            1
..    ...              ...            ...          ...
395  46.0          41000.0              1            0
396  51.0          23000.0              0            1
397  50.0          20000.0              1            0
398  36.0          33000.0              0            1
399  49.0          36000.0              1            0

[400 rows x 4 columns]
0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=123)
x_train
y_train

177    0
105    0
5      0
288    0
279    1
      ..
230    1
98     0
322    0
382    1
365    1
Name: Purchased, Length: 280, dtype: int64

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
x_train
x_test

array([[ 0.0510422 ,  1.29450114,  0.97879618, -0.97879618],
       [-0.23479413,  1.17420233, -1.02166316,  1.02166316],
       [-0.04423658,  0.30203594, -1.02166316,  1.02166316],
       [-0.61590925, -1.62274504,  0.97879618, -0.97879618],
       [ 0.0510422 , -0.1190099 ,  0.97879618, -0.97879618],
       [ 0.0510422 , -0.57013044,  0.97879618, -0.97879618],
       [-0.99702437, -0.32953282,  0.97879618, -0.97879618],
       [ 1.00382999,  2.07644342,  0.97879618, -0.97879618],
       [ 0.33687854,  0.54263357, -1.02166316,  1.02166316],
       [-0.71118803,  1.41479995,  0.97879618, -0.97879618],
       [-0.33007291, -0.78065336,  0.97879618, -0.97879618],
       [ 0.24159976,  0.27196124, -1.02166316,  1.02166316],
       [ 1.09910877, -0.1190099 , -1.02166316,  1.02166316],
       [-0.90174559, -0.75057866,  0.97879618, -0.97879618],
       [-0.42535169, -0.26938341,  0.97879618, -0.97879618],
       [ 1.48022389,  0.09151302, -1.02166316,  1.02166316],
       [-1.2828607 ,  0.45240946, -1.02166316,  1.02166316],
       [-0.04423658, -1.08140039,  0.97879618, -0.97879618],
       [-0.42535169, -0.54005574,  0.97879618, -0.97879618],
       [-0.23479413, -0.1190099 ,  0.97879618, -0.97879618],
       [-0.23479413, -1.41222212, -1.02166316,  1.02166316],
       [-0.04423658, -0.209234  ,  0.97879618, -0.97879618],
       [-1.09230314, -1.56259563,  0.97879618, -0.97879618],
       [-1.09230314,  1.47494936,  0.97879618, -0.97879618],
       [-0.80646681,  0.33211065, -1.02166316,  1.02166316],
       [-0.71118803,  1.98621931, -1.02166316,  1.02166316],
       [-1.09230314, -0.50998103,  0.97879618, -0.97879618],
       [ 1.48022389,  2.22681693,  0.97879618, -0.97879618],
       [ 0.0510422 , -0.29945811, -1.02166316,  1.02166316],
       [ 0.43215732,  0.18173713,  0.97879618, -0.97879618],
       [-0.33007291,  1.38472525, -1.02166316,  1.02166316],
       [-0.52063047,  0.51255887,  0.97879618, -0.97879618],
       [ 1.38494511, -1.44229682,  0.97879618, -0.97879618],
       [-1.7592546 , -1.29192331,  0.97879618, -0.97879618],
       [ 0.0510422 , -0.23930871, -1.02166316,  1.02166316],
       [-0.13951535,  2.25689163, -1.02166316,  1.02166316],
       [-0.23479413,  0.30203594, -1.02166316,  1.02166316],
       [ 0.43215732, -0.1190099 , -1.02166316,  1.02166316],
       [-0.33007291,  1.29450114, -1.02166316,  1.02166316],
       [ 0.43215732,  0.12158773, -1.02166316,  1.02166316],
       [-0.04423658,  0.33211065,  0.97879618, -0.97879618],
       [-0.13951535, -0.1791593 ,  0.97879618, -0.97879618],
       [-0.04423658,  0.15166243, -1.02166316,  1.02166316],
       [-0.80646681,  0.18173713, -1.02166316,  1.02166316],
       [ 1.95661778,  0.78323119,  0.97879618, -0.97879618],
       [-0.42535169, -1.2317739 ,  0.97879618, -0.97879618],
       [ 0.33687854,  0.09151302,  0.97879618, -0.97879618],
       [ 0.43215732,  2.40726515, -1.02166316,  1.02166316],
       [ 1.00382999, -1.08140039, -1.02166316,  1.02166316],
       [ 0.33687854, -0.50998103, -1.02166316,  1.02166316],
       [ 1.09910877, -1.2317739 , -1.02166316,  1.02166316],
       [-0.90174559, -0.29945811, -1.02166316,  1.02166316],
       [ 1.861339  ,  0.15166243, -1.02166316,  1.02166316],
       [ 0.24159976,  1.14412763, -1.02166316,  1.02166316],
       [ 2.05189656,  0.57270827,  0.97879618, -0.97879618],
       [ 0.81327243, -1.38214742, -1.02166316,  1.02166316],
       [-0.52063047, -1.53252093, -1.02166316,  1.02166316],
       [-0.04423658,  2.04636871,  0.97879618, -0.97879618],
       [-0.80646681, -0.78065336, -1.02166316,  1.02166316],
       [-1.66397582, -0.60020514, -1.02166316,  1.02166316],
       [-0.99702437,  2.04636871,  0.97879618, -0.97879618],
       [ 0.71799366, -1.41222212, -1.02166316,  1.02166316],
       [-0.52063047,  1.44487465,  0.97879618, -0.97879618],
       [ 1.76606022,  1.9260699 , -1.02166316,  1.02166316],
       [ 0.81327243, -0.84080277,  0.97879618, -0.97879618],
       [ 1.09910877,  0.57270827, -1.02166316,  1.02166316],
       [-0.04423658,  0.09151302, -1.02166316,  1.02166316],
       [ 1.38494511,  2.43733985, -1.02166316,  1.02166316],
       [-0.99702437,  0.60278297, -1.02166316,  1.02166316],
       [-1.09230314, -1.62274504,  0.97879618, -0.97879618],
       [-1.66397582, -1.38214742,  0.97879618, -0.97879618],
       [ 1.00382999,  0.63285768, -1.02166316,  1.02166316],
       [ 0.14632098, -0.81072806, -1.02166316,  1.02166316],
       [-0.80646681,  0.42233476,  0.97879618, -0.97879618],
       [ 1.28966633,  2.31704104,  0.97879618, -0.97879618],
       [-0.61590925, -1.05132569,  0.97879618, -0.97879618],
       [ 0.14632098,  1.9561446 ,  0.97879618, -0.97879618],
       [ 1.00382999, -1.1716245 ,  0.97879618, -0.97879618],
       [ 0.43215732,  0.33211065, -1.02166316,  1.02166316],
       [-0.13951535,  1.47494936, -1.02166316,  1.02166316],
       [-1.2828607 , -1.38214742, -1.02166316,  1.02166316],
       [ 1.00382999,  1.9561446 ,  0.97879618, -0.97879618],
       [-0.99702437,  0.45240946,  0.97879618, -0.97879618],
       [ 1.861339  , -1.29192331,  0.97879618, -0.97879618],
       [ 0.14632098, -0.23930871,  0.97879618, -0.97879618],
       [ 0.33687854,  0.33211065,  0.97879618, -0.97879618],
       [ 0.43215732, -0.1490846 , -1.02166316,  1.02166316],
       [ 2.14717534, -0.81072806, -1.02166316,  1.02166316],
       [-0.23479413, -0.75057866,  0.97879618, -0.97879618],
       [-1.85453338,  0.51255887,  0.97879618, -0.97879618],
       [ 2.05189656, -0.81072806,  0.97879618, -0.97879618],
       [ 1.95661778, -0.66035455,  0.97879618, -0.97879618],
       [ 0.81327243,  0.15166243,  0.97879618, -0.97879618],
       [ 2.14717534,  0.42233476, -1.02166316,  1.02166316],
       [-1.7592546 , -1.50244623, -1.02166316,  1.02166316],
       [ 1.09910877,  0.60278297, -1.02166316,  1.02166316],
       [ 1.00382999,  0.81330589,  0.97879618, -0.97879618],
       [-0.23479413, -0.90095217, -1.02166316,  1.02166316],
       [ 0.33687854, -1.1716245 ,  0.97879618, -0.97879618],
       [-1.09230314,  0.09151302,  0.97879618, -0.97879618],
       [-1.56869704,  0.57270827, -1.02166316,  1.02166316],
       [ 0.5274361 ,  1.29450114,  0.97879618, -0.97879618],
       [-0.80646681, -0.23930871, -1.02166316,  1.02166316],
       [-0.33007291, -1.32199801,  0.97879618, -0.97879618],
       [-1.66397582,  0.51255887, -1.02166316,  1.02166316],
       [ 2.14717534, -0.69042925,  0.97879618, -0.97879618],
       [-0.23479413,  0.18173713, -1.02166316,  1.02166316],
       [-1.2828607 , -0.41975692,  0.97879618, -0.97879618],
       [-0.61590925,  0.15166243, -1.02166316,  1.02166316],
       [ 0.81327243,  1.44487465, -1.02166316,  1.02166316],
       [ 0.90855121, -0.60020514,  0.97879618, -0.97879618],
       [-0.13951535,  0.18173713,  0.97879618, -0.97879618],
       [-0.52063047,  0.93360471, -1.02166316,  1.02166316],
       [-0.23479413, -0.29945811, -1.02166316,  1.02166316],
       [ 1.95661778, -1.38214742,  0.97879618, -0.97879618],
       [-0.80646681, -1.2317739 ,  0.97879618, -0.97879618],
       [-0.23479413,  0.24188654,  0.97879618, -0.97879618],
       [-0.23479413,  0.09151302, -1.02166316,  1.02166316],
       [ 1.00382999,  2.16666752, -1.02166316,  1.02166316],
       [-0.90174559, -1.11147509, -1.02166316,  1.02166316]])

In [15]:
from sklearn.svm import SVC
model=SVC(kernel='rbf',random_state=0)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))

0.8916666666666667

In [13]:
print(confusion_matrix(y_test,y_pred))

[[68  9]
 [ 4 39]]

In [14]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.88      0.91        77
           1       0.81      0.91      0.86        43

    accuracy                           0.89       120
   macro avg       0.88      0.90      0.88       120
weighted avg       0.90      0.89      0.89       120